#!/usr/bin/env bash
# Script to display DNS information about subdomains
# Usage: ./0-world_wide_web <domain> [subdomain]

display_info() {
    local domain=$1
    local subdomain=$2
    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk -v subdomain="$subdomain" '{ print "The subdomain " subdomain " is a " $4 " record and points to " $5}'
}

domain=$1
if [ "$#" -eq 2 ]; then
    display_info "$domain" "$2"
else
    display_info "$domain" "www"
    display_info "$domain" "lb-01"
    display_info "$domain" "web-01"
    display_info "$domain" "web-02"
fi